### ISSUE TITLE
undefined variable warnblock in line

### ISSUE THREAD

**Issue by Daimonion1980** [skerbis/do-form-5#6]
I got an error in modul output that the variable warnblock is not defined. and what should i say... the system is right

i couldn't find any line where warnblock is defined:

https://github.com/skerbis/do-form-5/blob/ccf3da414325a06381073114d41612d5c0ce74ec/doform5-ausgabe.php#L453

Error in my Redaxo installation. 

Notice: Undefined variable: warnblock in 
D:\Homepage\redaxo\include\classes\class.rex_article_base.inc.php(361) : eval()'d code on line 783

do i make something wrong or where is the issue?

**Comment by skerbis** [comment]
This is not an Error it's a notice
