### ISSUE TITLE
access to $FORM is not safe

### ISSUE THREAD

**Issue by Daimonion1980** [skerbis/do-form-5#7]
Tried to install doForm but stucks at the very first point.

My installation tried to acces variable $FORM on line 323:

https://github.com/skerbis/do-form-5/blob/ccf3da414325a06381073114d41612d5c0ce74ec/doform5-ausgabe.php#L323

but $FORM is empty cause Line 312 delivers no input.

https://github.com/skerbis/do-form-5/blob/master/doform5-ausgabe.php#L312

What is the issue?

**Comment by skerbis** [comment]
It's just a notice not an Error. You should not get the Notice now. The Module works fine.
