### ISSUE TITLE
xform syntax

### ISSUE THREAD

**Issue by cukabeka** [skerbis/do-form-5#8]
was ich mich immer schon gefragt habe: ich nutze do_form an sich gerne, was mich allerdings irritiert, ist, dass die syntax sich so sehr von xform unterscheidet. wäre es nicht möglich, das format anzupassen, so dass man formulardefinitionen zwsichen xform und do_form austauschen kann?

**Comment by skerbis** [comment]
do form basiert auf den REDAXO 3 - Formulagenerator ... also ein Urgroßvater von XFORM ... da werde ich nichts mehr machen.

**Comment by skerbis** [comment]
@cukabeka wenn du Lust hast, forken und umbauen ;-)

**Comment by cukabeka** [comment]
hm, weißt du spontan, wo im code das parsing stattfindet? dann kann ich das mal mit dem yform-code vergleichen, evtl lässt sich das ja einfach ersetzen..

**Comment by skerbis** [comment]
ne, do-form 6 https://github.com/skerbis/do-form-6
Der Nachfolger wird für yForm realisiert. - Aber das dauert noch was
